version: "3"
services:
  customNginx:
    build:
      context: nginx/
      args:
        - NAME=Nginx
        - STATUS=OK
    image: dimafrost/customnginx:1.0
    environment:
        - NAME=customNginx
    ports:
      - 8080:80

  pyapp:
    build: pyapp/
    image: dimafrost/pyapp:1.0
    ports:
      - 8081:8080

  customApache:
    build: apache/
    image: dimafrost/customapache:1.0
    environment:
      - NAME=Apache
      - STATUS=OK
    ports:
      - 8082:80