version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    environment:
      IMAGE_NAME: building-on-ci
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: download repo from git
          command:
            docker run -v ~/:/gitRep dimafrost/alpineforgit:1.1  git clone https://github.com/dima-frost/docker
      - run:
          name: docker-compose build
          command: |
            docker-compose build
      - run:
          name: docker-compose up
          command:  |
            docker-compose up -d
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker tag $DOCKERHUB_USERNAME/customapache:1.0 $DOCKERHUB_USERNAME/customapache:$TAG
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/customapache:$TAG
      - run:
          name: docker-compose down
          command: |
            docker-compose down