version: "3.8"
services:
  customNginx:
    build:
      context: ./
      args:
        - NAME=Nginx
        - STATUS=OK
    image: dimafrost/customnginx:1.1
    environment:
      - NAME=envNginx
    ports:
      - 8080:80